
development:

 email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
 email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
 mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
 mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
 domain_name: example.com 
 owner_email: <%= ENV["OWNER_EMAIL"] %>
 secret_key_base: 1200e95f5da834774f4bb7250d26db1c17d4faa6009c74592b57a2549c245194d5ec6ea327f8c1c74258704adf8111220cfa852c0bab9cb275dd604e96078e99

test:
  secret_key_base: bab9bf1a0a27ecab83beb9aba02621f1c9a7071fe8897d27b84eb937848f5b47217ced6b982368b5e679921bae55e4d226b415a5b171757e88e291f92b60b2d8

production:

 email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
 email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
 mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
 mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
 domain_name: <%= ENV["DOMAIN_NAME"] %>
 owner_email: <%= ENV["OWNER_EMAIL"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
